name: llm_niryo_cuda12
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - python-sounddevice
  - supervision
  - py-opencv
  - opencv
  - transformers
  - ultralytics
  - pyopenssl
  - pip:
      - torch==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - torchaudio==2.6.0+cu126
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - pyniryo2
      - pyniryo
