robots:
  niryo:
    default_workspace_id: niryo_ws2

    workspaces:
      - id: niryo_ws
        robot_type: niryo
        observation_pose:
          x: 0.173
          y: -0.002
          z: 0.277
          roll: -3.042
          pitch: 1.327
          yaw: -3.027
        image_shape: [640, 480, 3]

      - id: niryo_ws2
        robot_type: niryo
        observation_pose:
          x: 0.173
          y: -0.002
          z: 0.277
          roll: -3.042
          pitch: 1.327
          yaw: -3.027
        image_shape: [640, 480, 3]

      - id: niryo_ws_left
        robot_type: niryo
        observation_pose:
          x: 0.173
          y: 0.10
          z: 0.277
          roll: -3.042
          pitch: 1.327
          yaw: -3.027
        image_shape: [640, 480, 3]

      - id: niryo_ws_right
        robot_type: niryo
        observation_pose:
          x: 0.173
          y: -0.10
          z: 0.277
          roll: -3.042
          pitch: 1.327
          yaw: -3.027
        image_shape: [640, 480, 3]

    simulation_workspaces:
      - id: gazebo_1
        robot_type: niryo
        observation_pose:
          x: 0.18
          y: 0.0
          z: 0.36
          roll: 2.4
          pitch: 1.5708  # π/2
          yaw: 2.4
        image_shape: [640, 480, 3]

      - id: gazebo_2
        robot_type: niryo
        observation_pose:
          x: 0.18
          y: 0.15
          z: 0.36
          roll: 2.4
          pitch: 1.5708
          yaw: 2.4
        image_shape: [640, 480, 3]

      - id: gazebo_1_chocolate_bars
        robot_type: niryo
        observation_pose:
          x: 0.18
          y: 0.0
          z: 0.36
          roll: 0.0
          pitch: 1.8708  # π/2 + 0.3
          yaw: 0.0
        image_shape: [640, 480, 3]
